### ISSUE TITLE
`eval {}` is broken now

### ISSUE THREAD

**Issue by jpco** [wryun/es-shell#104]
Somehow #69 broke `eval` pretty badly, such that now I'm seeing
```
; eval {}
var.c:240: assertion failed (rootlist == &push->defnroot)
IOT instruction--core dumped
```
So.  Oops.

Just based on which lines of code were touched by each commit, it seems like it should have been #88 that did it, but actual git bisection says otherwise.

Incidentally, I just noticed that `trip.es` has several calls to `eval`, but none of them are of the form `eval {...}`!  So that seems like a gap to fix.

**Comment by wryun** [comment]
Revert first, ask questions later :) Thanks for tracking it down.
