### ISSUE TITLE
Incorrect permission mask usage in $&access ?

### ISSUE THREAD

**Issue by memreflect** [wryun/es-shell#126]
`$&access -rx filename` will succeed even if `$&access -r filename` would fail alone:

```
; echo > hello.sh '#!/bin/sh
echo hello world'
; chmod 111 hello.sh
; echo <={$&access -rx hello.sh}
0
; echo <={$&access -x hello.sh}
0
; echo <={$&access -r hello.sh}
Permission denied
; ./hello.sh
/bin/sh: cannot open ./hello.sh: Permission denied
```

For example, `%pathsearch` uses `-xf`, and if you use `$&access -xf /`, the result is an error message because `%and {$&access -x /} {$&access -f /}` is false.
Multiple permissions should be handled the same way (both the file type and all file permissions must match), but they are instead used like `%or {$&access -r hello.sh} {$&access -x hello.sh}` (the file type must match and any file permissions must match).

**Comment by jpco** [comment]
I agree the current behavior is confusing.  My "Chesterton's fence" sense is tingling -- is there some chance this behavior was inherited from another standard utility/function?  If not, I agree it should probably be changed (if so, then maybe it should be changed anyway).

**Comment by memreflect** [comment]
I'm honestly not sure if it was inherited from another utility or not.
The changes for the 0.8 release state that it "is similar to test from other shells" and "the name is different because the semantics are somewhat different".
Maybe the semantics were deliberate, or maybe the difference was the fact that `access -xf $name` would be written `test -x $name -a -f $name` or `test -x $name && test -f $name`.

On the other hand, the semantics could have been a bug that went unnoticed.
In 0.79, `%pathsearch` was defined as `fn-%pathsearch = $&pathsearch`, and there was no general-purpose `$&access` primitive to test things, so only the correct executable bit and the file type were tested to ensure a path referred to an executable file.

The "it's a bug" theory is a bit more credible when you consider that `x & mask` evaluates as "true" if at least one bit is set, which would previously have been the executable bit alone, and that's exactly what happens in `testperm()`.
Instead, `(x & mask) == mask` should be used to evaluate as "true" only if all bits are set.

**Comment by jpco** [comment]
I think that's enough to convince me this ought to change.  I'll let @wryun make the call on whether backwards compatibility overrides, though.

**Comment by wryun** [comment]
This is too obviously weird. If anyone's discovered this behaviour and relying on it, I blame them for not reporting it :laughing:

**Comment by memreflect** [comment]
I believe this behavior came from the old `$&pathsearch` primitive.
If you are just trying to determine whether something is executable, then it makes sense to simply use

```
return (permissions & EXEC);
```

Then `$&access` happened, blindly replacing `EXEC` with the permission mask corresponding to the flags provided, mistakenly ignoring the fact that C considers any nonzero integer to be "true":

```
/* EXEC & (READ | EXEC) => EXEC (true) */
return (permissions & mask) ? 0 : EACCES;
```
