### ISSUE TITLE
`$&sethistory` with no arguments still reads a history file

### ISSUE THREAD

**Issue by memreflect** [wryun/es-shell#135]
While looking at #133, i noticed that `$&sethistory` with no arguments (i.e. an empty list) results in calling `read_history(NULL)`, which results in reading `~/.history`.

There are some problems with this:

1. History will be loaded from that file, but new command lines won't be saved to it because `history = ()` still results in `$history` being an empty list.
2. `read_history(NULL)` does not consider `HOME` when the manual mentions `~/.history`; it instead relies entirely on `getpwent()` or whatever for tilde expansion.
3. `~/.history` is the default history file used by tcsh with a default timestamp format that includes a sign (i.e. `#{+|-}nnn`) while `read_history()` uses `#nnn` only, making them incompatible.
   Setting `history_comment_char = '#';` in `initinput()` doesn't change anything by itself &mdash; the tcsh timestamps are treated like normal shell comments that look like `#+1729429672`, which included in the history list.
   Removing the leading `+` (or `-`) character from all timestamps in the file makes `read_history()` correctly avoid loading the timestamped lines as shell comments, but the next execution of tcsh just ignores what it thinks are invalid timestamps in the history file and rewrites the commands to the file with new timestamps in the tcsh format.

Given all of these issues, i'm not sure `read_history()` should be called at all if `$&sethistory` was provided no arguments, making it effectively a no-op other than returning an empty list.

**Comment by jpco** [comment]
Ugh, ew.  I'm really glad you brought it up; I'd noticed this "helpful" behavior in the readline docs while I was working on #134 but it left my mind before I did anything about it.  Even if none of your good reasons were the case, it's plainly strange behavior to have `history = ()` explicitly meaning "no history file, please" and implicitly causing the shell to read from a history file.  If I want `history = ~/.history`, that's what I'll write.
