### ISSUE TITLE
Read from history file at startup?

### ISSUE THREAD

**Issue by spelufo** [wryun/es-shell#17]
With readline enabled, es is appending to my `~/.history` file but doesn't load it when it starts, so the only history I can search is the one since the session start. Is there a way of making it load the rest of the history?

**Comment by wryun** [comment]
If you look at https://github.com/wryun/es-shell/tree/readline-history you can see that there are only minor changes needed. Unfortunately, I haven't merged it to mainline yet because it needs some minor configuration tweaks (see commit message), but if you're prepared to build it yourself...

**Comment by wryun** [comment]
(oh, and the other issue is that doing that would probably break the odd version of editline which es supports)

**Comment by spelufo** [comment]
Great! Thank you
