### ISSUE TITLE
Is there any plan to release 0.9.2?

### ISSUE THREAD

**Issue by aosync** [wryun/es-shell#27]
Hello, thanks for maintaining the es shell.

I recently packaged es for KISS Linux and I am wondering if it is reasonable enough to release the next version soon. [A handful of sweet commits](https://github.com/wryun/es-shell/compare/v0.9.1...master) have been made since the release of 0.9.1 and I personally have used the master version for a few months without any major problems.

Have a good day.

**Comment by wryun** [comment]
Thanks for packaging and poking me about this!

I'll try to get around to it in the next couple of weeks - I've obviously been slack about getting things done for es, though I still use it as my interactive shell and for scripts I don't need to share. Things I want to deal with for 0.9.2 (mostly for my own reference):

- https://github.com/wryun/es-shell/pull/25/files
- make sure autoreconf --install works fine and start using that
- https://github.com/wryun/es-shell/tree/readline-history
- https://github.com/wryun/es-shell/issues/7

I probably won't get to the last one, but any PRs gratefully received.

**Comment by wryun** [comment]
Well, this is finally done. Sorry for the slightly ridiculous delay.
