### ISSUE TITLE
missing license for the repo

### ISSUE THREAD

**Issue by chenrui333** [wryun/es-shell#29]

**Comment by cryptorick** [comment]
It’s in the README. 
![B48AA0B0-2451-4490-AA68-13708FF3576D](https://user-images.githubusercontent.com/349810/87886962-ee8f7580-c9ee-11ea-94a1-2ced7aabdcf5.jpeg)

**Comment by Atemu** [comment]
This poses an issue for European contributors because they legally cannot waive their copyright.

A license like the CC0 which is technically copyrighted but effectively public domain would solve this issue and also just generally be clearer to everyone.

**Comment by Atemu** [comment]
You generally can't re-license stuff you're not the author of or are allowed to by a license, correct. The actual authors themselves would have to license it.

AFAIK, in the EU, contributing to a "Public Domain" project like this would mean that you still hold the copyright but promise not to enforce it. The copyright section in the README could actually be interpreted that way already.  
This means that such a contributor could freely decide that their code is no longer in the public domain at any point. Not retroactively of course but from that point onwards, you would not be able to do anything with their code and may even have to remove it.  
It also has some implications concerning liability and is generally an undersirable situation from what I understand; you need a license.

A simple compromise that you could do (and I think would be the best solution) would be to say that everything contributed from this point onwards will be licensed under the terms of the CC0 and that everything authored before is in the public domain.  
You'd have to check whether that's actually the case though of course as the work of contributors outside the US (if there are any) most likely *is not in the public domain currently*.  
It'd likely still be a bit messy but not nearly as bad as the mess that exists right now.

IANAL or any sort of expert on this but we just covered this topic in my IT law course in uni.

**Comment by wryun** [comment]
My current thinking on this is:

- I'm too lazy to email all the authors and get them to sign off on a proposal as I don't like spending time thinking about legal issues. If anyone wants to do this, go ahead! Any BSD/MIT/Unlicence/Apache thing is fine with me.
- I don't want to have some complex 'pre/post' licence situation that I don't properly understand and haven't seen used in practice (i.e. Atemu's solution above)
- this hasn't in the past prevented es being distributed by Debian, so practically it doesn't seem to be affecting us at the moment
- I kind of like that this project predates proper licensing

If someone has a clear proposal that they're willing to implement for how to fix this issue in a way that suits them, feel free to open a new issue.

For clarity, I've pushed the existing licence info into a COPYING file.
