### ISSUE TITLE
Is there a design limitation preventing support for rc-style switch statements?

### ISSUE THREAD

**Issue by hyphenrf** [wryun/es-shell#31]
Or is it just waiting to be implemented? I'm thinking about giving that a try honestly.

**Comment by hyphenrf** [comment]
so far I reached this:
```
fn switch match cases {
   let ((case body rest) = $cases)
    if { eval '~' $match $case } {
       $body
    }{ switch $match $rest }
}
```
which can be used like so:
```
switch (expr) (
   'pattern1' { body 1 }
   'pattern2' { body 2 }
   '*' { default body }
}
```
I don't think it's in any way better than a builtin syntax though

**Comment by wryun** [comment]
FYI, you can also implement without the recursion something like (avoiding the eval, which admittedly you need for complex things):

```
fn switch input cases { 
  for ((condition fragment) = $cases) { 
    if {~ $input $condition} { 
       $fragment 
    } 
  } 
}
```

**Comment by hyphenrf** [comment]
I don't really remember why I needed `eval`, but I remember needing it.  perhaps it was to avoid some form of pattern expansion or delay evaluation..? I'm not so sure.. it must've propagated from an earlier private implementation.

**Comment by wryun** [comment]
https://github.com/wryun/es-shell/pull/36
