### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by musvaage** [wryun/es-shell#50]
One of the co-authors of `es` wrote me historically he had a difficult time locating maintainers for the shell.

<hr>

`xs` appears to be abandonware

@wryun 

I'd enquire if you might consider suggesting to the xs author that the repo could be moved to wyrun/XS?

running ./buildscan.sh outputs warnings

the autotools build was converted to a meson build

not all meson versions work for the build (a python3 virtual environment with meson-0.54.x or 0.56.x works)

```
$ python3 -m venv xs_env
$ ~/xs_env/bin/python3 -m pip install --upgrade pip
Requirement already satisfied: pip in ./xs_env/lib/python3.9/site-packages (22.0.4)
$ ~/xs_env/bin/python3 -m pip install meson==0.56.2
Collecting meson==0.56.2
  Downloading meson-0.56.2.tar.gz (1.8 MB)
    ---------------------------------------- 1.8/1.8 MB 358.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: meson
  Building wheel for meson (pyproject.toml) ... done
  Created wheel for meson: filename=meson-0.56.2-py3-none-any.whl size=698109 sha256=3262eb59133294b2cc2af3da245c12ed05ce1a8cb1130f7269ad2ba22c83f845
  Stored in directory: /home/eric/.cache/pip/wheels/b8/1a/46/6990fd0de22ecf99596a8ee2d65e0c2e8bc3403872b57f33a5
Successfully built meson
Installing collected packages: meson
Successfully installed meson-0.56.2
$ source ~/xs_env/bin/activate
(xs_env) $ which meson
/home/eric/xs_env/bin/meson
(xs_env) $ 
```

A FSF associate wrote me they looked at math.xs, describing it as ugly.

In addition, it seems to mean using functional programming to
decompose a list.  That is a pain in the neck.

I don't know whether it is more bad or less bad than programming in
shell syntax.  But at least there' an excuse in that case: programming
is built around a command line syntax.  I see no excuse for making the
math.xs syntax so inconvenient.  If they're designing a new language
from zero, why take such a big step backard?

**Comment by wryun** [comment]
I've never actually looked at `xs`, I'm afraid, but I have limited enthusiasm for maintaining `es` let alone `xs` (in fact, if a contributor wanted to 'own' es themselves, I'd be happy to give it up).

Probably best to use the Discussions section - https://github.com/wryun/es-shell/discussions - if there's no specific issue.

**Comment by musvaage** [comment]
> use the Discussions

Of course.

Maybe the "notes" are of some interest to those considering further development of `es`.

IIRC, @pmarreck in another ticket had expressed interest in `xs`, the C++ implementation of the shell.
